<?php

/**
 * Implements hook_entity_presave().
 */

 use Drupal\Core\Entity\EntityInterface;

function task_93_entity_presave(EntityInterface $entity) {
  $country_id = \Drupal::state()->get('country_name');
  $country_name = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($country_id)->getName();
  $title = $entity->get('title')->value;

  if ($entity->getEntityTypeId() == 'node' && $entity->isNew()) {
    $entity->set('title', $title . ' - ' . $country_name);
  }
}