<?php

/**
 * Implements hook_entity_presave().
 */

 use Drupal\Core\Entity\EntityInterface;

function task_93_entity_presave(EntityInterface $entity) {
  $config = \Drupal::config('task_93.admin_settings');
  $settings_name = $config->get('task_93');
  $taxonomy_term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($settings_name)->getName();
  $title = $entity->get('title')->value;

  if ($entity->getEntityTypeId() == 'node' && $entity->isNew()) {
    $entity->set('title', $title . ' - ' . $taxonomy_term);
  }
}